export const actionTypes = {
    INIT: "__INIT__",
    TABLE_RESIZE: "TABLE_RESIZE",
    CELL_DATA_CHANGE: "CELL_DATA_CHANGE",
    CELL_STYLES_CHANGE: "CELL_STYLES_CHANGE",
    CELL_CURRENT_STYLES_CHANGE: "CELL_CURRENT_STYLES_CHANGE",
    TABLE_FOCUS_CAPTURE: "TABLE_FOCUS_CAPTURE",
    SHEET_NAME_CHANGE: "SHEET_NAME_CHANGE"
};
